service: default
runtime: java17

handlers:
  - url: /
    static_files: resources/public/index.html
    upload: resources/public/index.html
  - url: /stylesheets
    static_dir: resources/public/stylesheets
  # - url: /js
  #   static_dir: public/js
  - url: /api/.*
    script: auto
    
